from __future__ import annotations

import argparse
import sys
from pathlib import Path

from harness.backends import linux_admin
from harness.backends.base import Backend
from harness.commands import docker, require_command
from harness.settings import (
    DECOY_IFNAME,
    E2E_DIR,
    E2E_RESOURCE_PREFIX,
    NETFLECTOR_IFNAMES,
    NETFLECTOR_SOURCE_IFNAME,
    NETFLECTOR_TARGET_IFNAME,
    SEGMENT_V4_SUBNET,
    SEGMENT_V6_PREFIX,
    SEGMENTS,
)


class DockerBackend(Backend):
    def set_address(
        self, ifname: str, family: int, *, up: bool, cidr: str | None = None
    ) -> str | None:
        return linux_admin.set_address(self.admin, ifname, family, up=up, cidr=cidr)

    def add_decoy_route(self, dest_ip: str, ifname: str) -> bool:
        # SO_BINDTODEVICE confines the route lookup despite this competing host route.
        self.admin(f"ip route add {dest_ip}/32 dev {ifname}")
        return True

    PROBES_SURVIVE_DELETE = True
    ECHOES_OWN_FRAMES = True

    def __init__(self, args: argparse.Namespace, prefix: str) -> None:
        super().__init__(args, prefix)
        self.networks = {segment: f"{prefix}-{segment}" for segment in SEGMENTS}
        self.roles: dict[str, str] = {}  # role -> container name, in start order
        # segment -> (v4, v6) captured at delete_interface, re-pinned at recreate_interface.
        self._detached_addrs: dict[str, list[str]] = {}

    @staticmethod
    def require_available() -> None:
        require_command("docker")

    @staticmethod
    def preflight_clean() -> None:
        # A run killed mid-case -- a crashed engine, a cancelled CI job, a Ctrl-C -- leaves its
        # containers and networks behind. The names carry a per-run uuid so they never collide, but
        # the networks pin fixed subnets, so one survivor makes every later run fail at creation
        # with "Pool overlaps with other one on this address space". Containers go first: a network
        # with an endpoint still attached refuses to be removed.
        for kind, listing in (("container", ["ps", "-aq"]), ("network", ["network", "ls", "-q"])):
            found = docker(
                [*listing, "--filter", f"name=^{E2E_RESOURCE_PREFIX}"], echo=False
            ).stdout.split()
            if not found:
                continue
            print(f"preflight: removing {len(found)} stale e2e {kind}(s)", flush=True)
            remove = ["rm", "-f", *found] if kind == "container" else ["network", "rm", *found]
            docker(remove, check=False, echo=False)

    def setup_segments(self) -> None:
        # Both networks are dual-stack: IPv4 cases are unaffected, and IPv6 cases need the
        # bridges to carry IPv6 so netflector can listen on / emit to ff02::1. The subnets are
        # given explicitly (not IPAM-auto) so the recreate cases can pin the same --ip/--ip6 when
        # they reconnect the endpoint -- docker rejects a static address on an auto-subnet network.
        for segment in SEGMENTS:
            docker([
                "network", "create", "--driver", "bridge", "--ipv6",
                "--subnet", f"{SEGMENT_V4_SUBNET[segment]}.0/24",
                "--subnet", f"{SEGMENT_V6_PREFIX[segment]}::/64",
                self.networks[segment],
            ])

    def cleanup(self) -> None:
        for container in reversed(self.roles.values()):
            docker(["rm", "-f", container], check=False)
        self.roles.clear()
        for network in self.networks.values():
            docker(["network", "rm", network], check=False)

    def keep_artifacts(self) -> str:
        return f"Docker resources {self.prefix}"

    def start_netflector(self, config_path: Path) -> None:
        container = f"{self.prefix}-netflector"
        self.roles["netflector"] = container
        # Pin in-container interface names per network. Without this, Docker's interface naming
        # at start time is non-deterministic when multiple endpoints are attached, which made
        # netflector's SO_BINDTODEVICE land on the wrong bridge ~16% of runs. Using a non-"eth"
        # prefix avoids the prefix-collision caveat in moby/moby#49155. Requires Docker 28.0+
        # (the com.docker.network.endpoint.ifname driver-opt).
        docker(
            [
                "create",
                "--name",
                container,
                "--network",
                f"name={self.networks['source']},driver-opt=com.docker.network.endpoint.ifname={NETFLECTOR_SOURCE_IFNAME}",
                "--network",
                f"name={self.networks['target']},driver-opt=com.docker.network.endpoint.ifname={NETFLECTOR_TARGET_IFNAME}",
                # Skip Duplicate Address Detection on the link-local addresses. Without this the
                # kernel's autogenerated fe80:: is tentative (unusable) when netflector resolves
                # at startup, so it falls back to the Docker-assigned ULA as its sole v6 source and
                # never distinguishes link-local from routable -- masking the per-scope source
                # selection. With DAD off the fe80:: is usable immediately, so v6 (link-local) and
                # v6-routable (ULA) differ, as on a real interface.
                "--sysctl",
                "net.ipv6.conf.default.accept_dad=0",
                "--cap-add",
                "NET_RAW",
                "--mount",
                f"type=bind,source={config_path},target=/etc/netflector/config.toml,readonly",
                self.args.image,
                "/etc/netflector/config.toml",
            ]
        )
        docker(["start", container])
        self.enable_hairpin()

    def enable_hairpin(self) -> None:
        # ECHOES_OWN_FRAMES is the harness's doing, not a daemon default: a bridge port hands a
        # frame back to its own sender only in hairpin mode, which Docker Desktop sets by default
        # but Docker Engine sets only with the userland proxy off. Turn it on so the mirrored DIAL
        # cases meet the echo they exist to exercise on any daemon. Each in-container interface
        # names its host-side veth by ifindex (iflink); a host-namespace helper resolves that
        # through sysfs to the bridge port and takes the flag. Where the ports aren't reachable
        # (nothing resolves), the daemon's own default stands.
        links = self.admin(
            "".join(
                f"cat /sys/class/net/{name}/iflink 2>/dev/null || :; "
                for name in NETFLECTOR_IFNAMES.values()
            ),
            capture=True,
        ).split()
        script = (
            f"for link in {' '.join(links)}; do "
            "for d in /sys/class/net/*; do "
            '[ "$(cat "$d/ifindex" 2>/dev/null)" = "$link" ] || continue; '
            '[ -e "$d/brport/hairpin_mode" ] || continue; '
            'echo 1 > "$d/brport/hairpin_mode"; basename "$d"; '
            "done; done"
        )
        ports = docker(
            ["run", "--rm", "--privileged", "--network", "host",
             self.args.helper_image, "sh", "-ec", script],
            echo=False,
        ).stdout.split()
        if ports:
            print(f"hairpin enabled on {' '.join(ports)}", flush=True)
        else:
            print("no bridge port reachable for hairpin; the daemon's default stands", flush=True)

    def start_probe(
        self, role: str, segment: str, ifname: str, probe_args: list[str], *,
        detach: bool = True, pin_address: bool = False,
    ) -> None:
        container = f"{self.prefix}-{role}"
        self.roles[role] = container
        command = ["run"]
        if detach:
            command.append("-d")
        # Pin the helper's interface name so the probe can scope multicast egress / group
        # joins to it deterministically (see start_netflector for the rationale).
        network = f"name={self.networks[segment]},driver-opt=com.docker.network.endpoint.ifname={ifname}"
        if pin_address:
            network += f",ip={self.helper_address(segment, 4)},ip6={self.helper_address(segment, 6)}"
        command += [
            "--name",
            container,
            "--network",
            network,
            "--mount",
            f"type=bind,source={E2E_DIR},target=/e2e,readonly",
            self.args.helper_image,
            "python3",
            "/e2e/probe.py",
            *probe_args,
        ]
        docker(command)

    def helper_ifname(self, requested: str) -> str:
        return requested

    def wait(self, role: str) -> int:
        return int(docker(["wait", self.roles[role]], echo=False).stdout.strip())

    def logs(self, role: str) -> tuple[str, str]:
        result = docker(["logs", self.roles[role]], check=False, echo=False)
        return result.stdout, result.stderr

    def status(self, role: str) -> tuple[bool, str]:
        result = docker(
            ["inspect", "-f", "{{.State.Running}} {{.State.ExitCode}}", self.roles[role]],
            check=False,
            echo=False,
        )
        if result.returncode != 0:
            # A vanished container must fail the wait immediately, not spin out the ready
            # timeout; any other inspect failure (a daemon hiccup) is worth retrying.
            if "no such object" in result.stderr.lower():
                return False, "container no longer exists"
            return True, "unknown"
        state = result.stdout.strip()
        return not state.startswith("false "), state

    def remove(self, role: str) -> None:
        container = self.roles.pop(role, None)
        if container is not None:
            docker(["rm", "-f", container], check=False, echo=False)

    def stop_netflector(self, grace_seconds: int) -> int:
        docker(["stop", "-t", str(grace_seconds), self.roles["netflector"]])
        return self.wait("netflector")

    def stop_probe(self, role: str, grace_seconds: int) -> None:
        docker(["stop", "-t", str(grace_seconds), self.roles[role]], check=False, echo=False)

    def admin(self, script: str, *, capture: bool = False) -> str:
        # Address/route changes need CAP_NET_ADMIN and a writable /proc/sys, which the netflector
        # container (scratch image, NET_RAW only) has by neither. Run a throwaway privileged
        # container in netflector's network namespace, so `ip addr` / the disable_ipv6 sysctl
        # act on the very interfaces netflector watches -- without widening netflector's
        # own privileges.
        result = docker([
            "run", "--rm", "--privileged", "--network", f"container:{self.roles['netflector']}",
            self.args.helper_image, "sh", "-ec", script,
        ])
        return result.stdout.strip() if capture else ""

    def _container_ip(self, container: str, network: str) -> str:
        fmt = '{{(index .NetworkSettings.Networks "' + network + '").IPAddress}}'
        ip = docker(["inspect", "-f", fmt, container]).stdout.strip()
        if not ip:
            raise RuntimeError(f"no IPv4 address for {container} on {network}")
        return ip

    def delete_interface(self, segment: str) -> None:
        # Detaching the bridge endpoint destroys the veth pair, the in-container interface
        # included. Capture the endpoint's addresses first, so the reconnect can pin them.
        container = self.roles["netflector"]
        network = self.networks[segment]
        fmt = (
            '{{(index .NetworkSettings.Networks "' + network + '").IPAddress}}'
            '|{{(index .NetworkSettings.Networks "' + network + '").GlobalIPv6Address}}'
        )
        addrs = docker(["inspect", "-f", fmt, container], echo=False).stdout.strip()
        self._detached_addrs[segment] = addrs.split("|")
        docker(["network", "disconnect", network, container])

    def recreate_interface(self, segment: str) -> None:
        # Reconnect under the same pinned interface name and addresses: a fresh veth, a fresh
        # kernel identity. The driver-opt on connect needs the same Docker 28.0+ as create
        # (see start_netflector).
        v4, v6 = self._detached_addrs.pop(segment)
        command = [
            "network", "connect",
            "--driver-opt", f"com.docker.network.endpoint.ifname={NETFLECTOR_IFNAMES[segment]}",
            "--ip", v4,
        ]
        if v6:
            command += ["--ip6", v6]
        docker([*command, self.networks[segment], self.roles["netflector"]])
        self.enable_hairpin()  # the fresh veth comes up with the daemon's default

    def add_decoy_interface(self) -> None:
        # The privileged admin sidecar shares netflector's network namespace, so the veth
        # lands where the freed index lived. Linux never reuses indexes, so the decoy is inert
        # here -- it runs anyway to keep the case uniform across backends (and exercises
        # netflector's unwatched-churn policy for free).
        self.admin(f"ip link add {DECOY_IFNAME} type veth peer name {DECOY_IFNAME}p")

    def remove_decoy_interface(self) -> None:
        self.admin(f"ip link del {DECOY_IFNAME}")

    def netflector_ip(self, segment: str) -> str:
        return self._container_ip(self.roles["netflector"], self.networks[segment])

    def probe_ip(self, role: str, segment: str) -> str:
        return self._container_ip(self.roles[role], self.networks[segment])

    def print_diagnostics(self) -> None:
        for role, container in self.roles.items():
            inspect = docker(
                ["inspect", "-f", "{{.State.Status}} {{.State.ExitCode}}", container], check=False
            )
            if inspect.returncode == 0:
                print(f"{container}: {inspect.stdout.strip()}", file=sys.stderr, flush=True)

            out, err = self.logs(role)
            if out or err:
                print(f"--- logs: {container} ---", file=sys.stderr, flush=True)
                if out:
                    print(out, end="", file=sys.stderr, flush=True)
                if err:
                    print(err, end="", file=sys.stderr, flush=True)

        for network in self.networks.values():
            inspect = docker(["network", "inspect", network], check=False)
            if inspect.returncode == 0 and inspect.stdout:
                print(f"--- network: {network} ---", file=sys.stderr, flush=True)
                print(inspect.stdout, end="", file=sys.stderr, flush=True)
