from __future__ import annotations

from cases.models import TestCase
from fixtures import (
    MDNS_GROUP_V4,
    MDNS_GROUP_V6,
    MDNS_PORT,
    MDNS_QUERY_HEX,
    MDNS_RESPONSE_HEX,
    MDNS_RESPONSE_LINK_LOCAL_HEX,
    MDNS_RESPONSE_MIXED_HEX,
    MDNS_SHORT_QUERY_HEX,
    MDNS_WRONG_PORT,
)

# mDNS reflection is directional: queries relay source->target ("forward"), responses
# target->source ("reverse"). Both are relayed verbatim, so the receiver asserts the exact bytes
# it sent. The drop cases assert nothing arrives (the wrong direction, a too-short payload, or a
# port the dispatcher filter never passes).
MDNS_CASES = [
    TestCase(
        name="reflects_mdns_query",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_QUERY_HEX,
        expect_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
    ),
    # Two per-device entries on one pair share the query leg; the receiver fails on a second copy.
    TestCase(
        name="per_device_entries_relay_a_query_once",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_QUERY_HEX,
        expect_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
        config="config-per-device.toml",
    ),
    TestCase(
        name="reflects_mdns_response",
        send_source_port=MDNS_PORT,
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_RESPONSE_HEX,
        expect_payload_hex=MDNS_RESPONSE_HEX,
        group=MDNS_GROUP_V4,
        direction="reverse",
    ),
    TestCase(
        name="reflects_mdns_query_ipv6",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_QUERY_HEX,
        expect_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V6,
        family=6,
        direction="forward",
    ),
    TestCase(
        name="reflects_mdns_response_ipv6",
        send_source_port=MDNS_PORT,
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_RESPONSE_HEX,
        expect_payload_hex=MDNS_RESPONSE_HEX,
        group=MDNS_GROUP_V6,
        family=6,
        direction="reverse",
    ),
    # A routable address beside the link-local one rescues the response from suppression.
    TestCase(
        name="reflects_mdns_response_with_mixed_addresses",
        send_source_port=MDNS_PORT,
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_RESPONSE_MIXED_HEX,
        expect_payload_hex=MDNS_RESPONSE_MIXED_HEX,
        group=MDNS_GROUP_V4,
        direction="reverse",
    ),
    # Every address is link-local, so the response is suppressed rather than relayed.
    # A response from any port but 5353 is not one (RFC 6762 §6), so it stays where it was sent.
    TestCase(
        name="ignores_mdns_response_from_another_port",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=1.5,
        send_payload_hex=MDNS_RESPONSE_HEX,
        group=MDNS_GROUP_V4,
        direction="reverse",
    ),
    TestCase(
        name="ignores_mdns_link_local_only_response",
        send_source_port=MDNS_PORT,
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=1.5,
        send_payload_hex=MDNS_RESPONSE_LINK_LOCAL_HEX,
        group=MDNS_GROUP_V4,
        direction="reverse",
    ),
    # Against the one-way directions: a query from the target and a response from the source
    # reflect once the entry relays both ways.
    TestCase(
        name="bidirectional_reflects_mdns_query_from_target",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_QUERY_HEX,
        expect_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="reverse",
        config="config-bidirectional.toml",
    ),
    TestCase(
        name="bidirectional_reflects_mdns_response_from_source",
        send_source_port=MDNS_PORT,
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_RESPONSE_HEX,
        expect_payload_hex=MDNS_RESPONSE_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
        config="config-bidirectional.toml",
    ),
    # A query sent target->source hits the target's response-only handler and is dropped.
    TestCase(
        name="ignores_mdns_query_in_response_direction",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=1.5,
        send_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="reverse",
    ),
    # A response sent source->target hits the source's query-only handler and is dropped.
    TestCase(
        name="ignores_mdns_response_in_query_direction",
        send_source_port=MDNS_PORT,
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=1.5,
        send_payload_hex=MDNS_RESPONSE_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
    ),
    # 8 bytes < the 12-byte DNS header, so classify() returns None and drops it.
    TestCase(
        name="ignores_mdns_too_short_query",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=1.5,
        send_payload_hex=MDNS_SHORT_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
    ),
    # The dispatcher filter pins dst_port=5353, so a 5354 datagram never reaches a handler.
    TestCase(
        name="ignores_mdns_wrong_port",
        send_port=MDNS_WRONG_PORT,
        receive_port=MDNS_WRONG_PORT,
        expect_mac=None,
        timeout_seconds=1.5,
        send_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
    ),
    # Single-family gating (address_family = "ipv4"): the reflector reflects v4 mDNS but never joins
    # the v6 group or registers a v6 handler, so v6 is ignored. The v4 case is the positive control —
    # it proves the reflector is live, so the v6 expect-none is a real "gated out", not a dead reflector.
    TestCase(
        name="ipv4_only_reflector_reflects_mdns_query",
        config="config-family.toml",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=5.0,
        send_payload_hex=MDNS_QUERY_HEX,
        expect_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V4,
        direction="forward",
    ),
    TestCase(
        name="ipv4_only_reflector_ignores_mdns_query_ipv6",
        config="config-family.toml",
        send_port=MDNS_PORT,
        receive_port=MDNS_PORT,
        expect_mac=None,
        timeout_seconds=2.0,
        send_payload_hex=MDNS_QUERY_HEX,
        group=MDNS_GROUP_V6,
        family=6,
        direction="forward",
    ),
]
