#!/usr/bin/env bash
# Regenerate ci/freebsd.env: pin a FreeBSD release plus the SHA pins for its
# artifacts (amd64 + arm64 VM images and base.txz link sysroots), fetched from
# the official CHECKSUM.SHA512 / MANIFEST files. With no argument it re-pins
# the release already in freebsd.env -- the way to complete a Renovate bump
# PR, which can only edit RELEASE and leaves the hashes stale (the checksum
# gates keep CI red until this runs). RUST_NIGHTLY (the arm64 toolchain
# bridge) is carried over from freebsd.env, or seeded from the environment.
#
#   ci/freebsd-pin.sh        # refresh hashes for the pinned release
#   ci/freebsd-pin.sh 14.5   # move the pin to a new release
set -euo pipefail
cd "$(dirname "$0")"

[ -f freebsd.env ] && . ./freebsd.env
RELEASE=${1:-${RELEASE:?no freebsd.env yet; pass a release, e.g. 14.4}}
RUST_NIGHTLY=${RUST_NIGHTLY:?not in freebsd.env or the environment; e.g. RUST_NIGHTLY=2026-07-10}

mirror="https://download.freebsd.org/releases"
image_sha() { # $1 = image url; the checksums sit beside the image
    curl -fsSL "${1%/*}/CHECKSUM.SHA512" |
        awk -v img="(${1##*/})" '$1 == "SHA512" && $2 == img { print $4 }'
}
base_sha() { # $1 = base.txz url; the MANIFEST sits beside it
    curl -fsSL "${1%/*}/MANIFEST" |
        awk '$1 == "base.txz" { print $2 }'
}

# The mirror's naming conventions drift (14.2's images said "CLOUDINIT.ufs",
# 14.4's say "CLOUDINIT-ufs"; base paths mix amd64 and arm64/aarch64), so
# every URL is pinned alongside its hash: a wrong name or path fails the
# checksum lookup right here, not in a lane.
image_url_amd64="$mirror/VM-IMAGES/${RELEASE}-RELEASE/amd64/Latest/FreeBSD-${RELEASE}-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz"
image_url_arm64="$mirror/VM-IMAGES/${RELEASE}-RELEASE/aarch64/Latest/FreeBSD-${RELEASE}-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-ufs.qcow2.xz"
base_url_amd64="$mirror/amd64/${RELEASE}-RELEASE/base.txz"
base_url_arm64="$mirror/arm64/aarch64/${RELEASE}-RELEASE/base.txz"
image_sha512_amd64=$(image_sha "$image_url_amd64")
image_sha512_arm64=$(image_sha "$image_url_arm64")
base_sha256_amd64=$(base_sha "$base_url_amd64")
base_sha256_arm64=$(base_sha "$base_url_arm64")
for v in image_sha512_amd64 image_sha512_arm64 base_sha256_amd64 base_sha256_arm64; do
    [ -n "${!v}" ] || { echo "error: no checksum for $v at $RELEASE" >&2; exit 1; }
done

cat > freebsd.env <<EOF
# Pinned FreeBSD release for the ci/freebsd-*.sh scripts, with the official
# hashes of the artifacts fetched at run time: the amd64 + arm64 VM images
# and the base.txz sets the link sysroots come from. Generated by
# ci/freebsd-pin.sh -- edit that, not this. Renovate bumps RELEASE when a new
# 14.x point release ships (custom manager in renovate.json; majors move by
# hand: the oldest supported major gives static binaries the widest reach).
# Renovate cannot refresh the hashes, so its bump PR stays red on the
# checksum gates until \`ci/freebsd-pin.sh\` runs on its branch.
# renovate: datasource=endoflife-date depName=freebsd
RELEASE=$RELEASE
IMAGE_URL_AMD64=$image_url_amd64
IMAGE_URL_ARM64=$image_url_arm64
IMAGE_SHA512_AMD64=$image_sha512_amd64
IMAGE_SHA512_ARM64=$image_sha512_arm64
BASE_URL_AMD64=$base_url_amd64
BASE_URL_ARM64=$base_url_arm64
BASE_SHA256_AMD64=$base_sha256_amd64
BASE_SHA256_ARM64=$base_sha256_arm64
# aarch64-unknown-freebsd has no stable rust dist until 1.98, so the
# freebsd-arm64 lanes build with this pinned dated nightly (rustup verifies
# it against the immutable channel manifest). Delete once rust-toolchain.toml
# reaches 1.98; the lanes then build with the pinned stable like amd64.
RUST_NIGHTLY=$RUST_NIGHTLY
EOF
echo "pinned FreeBSD $RELEASE (amd64 + arm64), rust nightly $RUST_NIGHTLY" >&2
