#!/usr/bin/env bash
# Regenerate a ci/freebsd<major>.env pin file: a FreeBSD release plus the SHA pins for its
# artifacts (amd64 + arm64 VM images and base.txz link sysroots), fetched from
# the official CHECKSUM.SHA512 / MANIFEST files. With no argument it refreshes
# every pin file at its current release -- the way to complete a Renovate bump
# PR, which can only edit RELEASE and leaves the hashes stale (the checksum
# gates keep CI red until this runs). The freebsd-arm64 nightly bridge lives
# separately in ci/freebsd-nightly.env; this script does not touch it.
#
#   ci/freebsd-pin.sh          # refresh the hashes of every pinned release
#   ci/freebsd-pin.sh 14.5     # move the 14 pin to 14.5 (the file follows the major)
#   ci/freebsd-pin.sh 15.1     # same for 15; creates freebsd15.env if it is new
set -euo pipefail
cd "$(dirname "$0")"

[ $# -le 1 ] || { echo "usage: freebsd-pin.sh [release]" >&2; exit 64; }

mirror="https://download.freebsd.org/releases"
image_sha() { # $1 = image url; the checksums sit beside the image
    curl -fsSL "${1%/*}/CHECKSUM.SHA512" |
        awk -v img="(${1##*/})" '$1 == "SHA512" && $2 == img { print $4 }'
}
base_sha() { # $1 = base.txz url; the MANIFEST sits beside it
    curl -fsSL "${1%/*}/MANIFEST" |
        awk '$1 == "base.txz" { print $2 }'
}

# The mirror's naming conventions drift (14.2's images said "CLOUDINIT.ufs",
# 14.4's say "CLOUDINIT-ufs"; base paths mix amd64 and arm64/aarch64), so
# every URL is pinned alongside its hash: a wrong name or path fails the
# checksum lookup right here, not in a lane.
pin_one() { # $1 = release, e.g. 14.4; writes freebsd<major>.env
    local release=$1 out="freebsd${1%%.*}.env"
    local image_url_amd64="$mirror/VM-IMAGES/${release}-RELEASE/amd64/Latest/FreeBSD-${release}-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz"
    local image_url_arm64="$mirror/VM-IMAGES/${release}-RELEASE/aarch64/Latest/FreeBSD-${release}-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-ufs.qcow2.xz"
    local base_url_amd64="$mirror/amd64/${release}-RELEASE/base.txz"
    local base_url_arm64="$mirror/arm64/aarch64/${release}-RELEASE/base.txz"
    local image_sha512_amd64 image_sha512_arm64 base_sha256_amd64 base_sha256_arm64
    image_sha512_amd64=$(image_sha "$image_url_amd64")
    image_sha512_arm64=$(image_sha "$image_url_arm64")
    base_sha256_amd64=$(base_sha "$base_url_amd64")
    base_sha256_arm64=$(base_sha "$base_url_arm64")
    for v in image_sha512_amd64 image_sha512_arm64 base_sha256_amd64 base_sha256_arm64; do
        [ -n "${!v}" ] || { echo "error: no checksum for $v at $release" >&2; exit 1; }
    done
    cat > "$out" <<EOF
# Pinned FreeBSD release for the ci/freebsd-*.sh scripts, with the official
# hashes of the artifacts fetched at run time: the amd64 + arm64 VM images
# and the base.txz sets the link sysroots come from. Generated by
# ci/freebsd-pin.sh -- edit that, not this. Renovate bumps RELEASE when a new
# ${release%%.*}.x point release ships (custom manager in renovate.json; majors move by
# hand: the oldest supported major gives static binaries the widest reach).
# Renovate cannot refresh the hashes, so its bump PR stays red on the
# checksum gates until \`ci/freebsd-pin.sh\` runs on its branch.
# renovate: datasource=endoflife-date depName=freebsd
RELEASE=$release
IMAGE_URL_AMD64=$image_url_amd64
IMAGE_URL_ARM64=$image_url_arm64
IMAGE_SHA512_AMD64=$image_sha512_amd64
IMAGE_SHA512_ARM64=$image_sha512_arm64
BASE_URL_AMD64=$base_url_amd64
BASE_URL_ARM64=$base_url_arm64
BASE_SHA256_AMD64=$base_sha256_amd64
BASE_SHA256_ARM64=$base_sha256_arm64
EOF
    echo "pinned FreeBSD $release (amd64 + arm64) into $out" >&2
}

if [ $# -eq 1 ]; then
    pin_one "$1"
else
    found=
    for f in freebsd[0-9]*.env; do
        [ -f "$f" ] || continue
        found=1
        release=$(. "./$f" && echo "$RELEASE")
        pin_one "$release"
    done
    [ -n "$found" ] || { echo "error: no freebsd<major>.env to refresh; pass a release" >&2; exit 1; }
fi
