#!/usr/bin/env bash
# Regenerate ci/freebsd.env: pin a FreeBSD release plus the SHA pins for its
# VM image and base.txz, fetched from the official CHECKSUM.SHA512 / MANIFEST
# files. With no argument it re-pins the release already in freebsd.env --
# the way to complete a Renovate bump PR, which can only edit RELEASE and
# leaves the hashes stale (the checksum gates keep CI red until this runs).
#
#   ci/freebsd-pin.sh        # refresh hashes for the pinned release
#   ci/freebsd-pin.sh 14.5   # move the pin to a new release
set -euo pipefail
cd "$(dirname "$0")"

[ -f freebsd.env ] && . ./freebsd.env
RELEASE=${1:-${RELEASE:?no freebsd.env yet; pass a release, e.g. 14.4}}

mirror="https://download.freebsd.org/releases"
image="FreeBSD-${RELEASE}-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz"
image_sha512=$(curl -fsSL "$mirror/VM-IMAGES/${RELEASE}-RELEASE/amd64/Latest/CHECKSUM.SHA512" |
    awk -v img="($image)" '$1 == "SHA512" && $2 == img { print $4 }')
base_sha256=$(curl -fsSL "$mirror/amd64/${RELEASE}-RELEASE/MANIFEST" |
    awk '$1 == "base.txz" { print $2 }')
[ -n "$image_sha512" ] || { echo "error: no SHA512 for $image" >&2; exit 1; }
[ -n "$base_sha256" ] || { echo "error: no SHA256 for base.txz" >&2; exit 1; }

cat > freebsd.env <<EOF
# Pinned FreeBSD release for the ci/freebsd-*.sh scripts, with the official
# hashes of the two artifacts fetched at run time. Generated by
# ci/freebsd-pin.sh -- edit that, not this. Renovate bumps RELEASE when a new
# 14.x point release ships (custom manager in renovate.json; majors move by
# hand: the oldest supported major gives static binaries the widest reach).
# Renovate cannot refresh the hashes, so its bump PR stays red on the
# checksum gates until \`ci/freebsd-pin.sh\` runs on its branch.
# renovate: datasource=endoflife-date depName=freebsd
RELEASE=$RELEASE
IMAGE_SHA512=$image_sha512
BASE_SHA256=$base_sha256
EOF
echo "pinned FreeBSD $RELEASE" >&2
