#!/usr/bin/env bash
# Regenerate ci/supply-chain.env: the cargo-audit and cargo-deny releases the supply-chain lane
# runs, each with the URL of the linux-musl tarball and its SHA256. With no argument it re-hashes
# the versions already pinned -- the way to complete a Renovate bump PR, which can only edit the
# VERSION lines and leaves the hashes stale (the checksum gate keeps the lane red until this runs).
#
#   ci/supply-chain-pin.sh            # re-hash the pinned versions
#   ci/supply-chain-pin.sh --latest   # move both tools to their newest release, then hash
#
# To pin a specific version, edit its VERSION line and run with no argument.
set -euo pipefail
cd "$(dirname "$0")"

[ $# -eq 0 ] || [ "${1:-}" = --latest ] || { echo "usage: supply-chain-pin.sh [--latest]" >&2; exit 64; }

# The two projects tag differently: cargo-audit lives in a workspace and prefixes its tag, while
# cargo-deny releases a bare version. Each URL is pinned alongside its hash rather than rebuilt in
# the workflow, so a naming change fails here and not in a lane (the prefixed tag needs %2F in the
# path, which is exactly the kind of detail that rots when it is spelled out twice).
audit_url() { echo "https://github.com/rustsec/rustsec/releases/download/cargo-audit%2Fv$1/cargo-audit-x86_64-unknown-linux-musl-v$1.tgz"; }
deny_url() { echo "https://github.com/EmbarkStudios/cargo-deny/releases/download/$1/cargo-deny-$1-x86_64-unknown-linux-musl.tar.gz"; }

latest_audit() { gh api repos/rustsec/rustsec/releases --jq '[.[] | select(.tag_name | startswith("cargo-audit/v"))][0].tag_name' | sed 's|cargo-audit/v||'; }
latest_deny() { gh api repos/EmbarkStudios/cargo-deny/releases/latest --jq .tag_name; }

sha256_of() { # $1 = url; hash what CI will actually download
    local tmp; tmp=$(mktemp)
    curl -fsSL -o "$tmp" "$1"
    if command -v sha256sum > /dev/null; then sha256sum "$tmp" | cut -d' ' -f1; else shasum -a 256 "$tmp" | cut -d' ' -f1; fi
    rm -f "$tmp"
}

if [ "${1:-}" = --latest ]; then
    audit_version=$(latest_audit)
    deny_version=$(latest_deny)
else
    # shellcheck source=ci/supply-chain.env
    . ./supply-chain.env
    audit_version=$AUDIT_VERSION
    deny_version=$DENY_VERSION
fi

audit_url=$(audit_url "$audit_version")
deny_url=$(deny_url "$deny_version")
audit_sha256=$(sha256_of "$audit_url")
deny_sha256=$(sha256_of "$deny_url")

# cargo-deny publishes its own checksum beside the tarball. Comparing catches a truncated or
# swapped download here rather than pinning it; cargo-audit publishes none, so it has no such check.
published=$(curl -fsSL "$deny_url.sha256" | cut -d' ' -f1)
[ "$published" = "$deny_sha256" ] || { echo "error: cargo-deny $deny_version hash $deny_sha256 does not match its published $published" >&2; exit 1; }

cat > supply-chain.env <<EOF
# Pinned dependency-policy tools for ci-supply-chain.yml, each with the URL the lane downloads and
# its SHA256. Generated by ci/supply-chain-pin.sh -- edit that, not this.
#
# Fetched and verified rather than run through the upstream actions: those curl the same binaries
# with no checksum, so pinning the action pins its Dockerfile and not what it executes.
#
# Renovate bumps the versions (custom manager in renovate.json). It cannot refresh the hashes or
# the URLs, so its PR stays red on the checksum gate until \`ci/supply-chain-pin.sh\` runs on its
# branch.
# renovate: datasource=github-releases depName=rustsec/rustsec
AUDIT_VERSION=$audit_version
AUDIT_URL=$audit_url
AUDIT_SHA256=$audit_sha256
# renovate: datasource=github-releases depName=EmbarkStudios/cargo-deny
DENY_VERSION=$deny_version
DENY_URL=$deny_url
DENY_SHA256=$deny_sha256
EOF

echo "pinned cargo-audit $audit_version and cargo-deny $deny_version into supply-chain.env" >&2
