//! netflector: reflects link-local service traffic (Wake-on-LAN, mDNS, SSDP, WS-Discovery,
//! and an optional DIAL proxy) between two network interfaces.
//!
//! The behavior lives in this library crate so it stays testable in-process;
//! the binary (`src/main.rs`) is a thin shim over [`run`].

mod capture;
mod cli;
mod config;
mod dispatch;
mod error;
mod interface;
mod libcex;
mod logging;
mod memory_report;
mod net;
mod reactor;
mod reflector;
mod sys;

pub use self::error::{Error, Result};
pub use self::logging::init as init_logging;

use std::ffi::OsString;
use std::path::Path;

use self::capture::Capture;
use self::cli::Invocation;
use self::config::Config;
use self::dispatch::PacketDispatcher;
use self::reactor::Reactor;
use self::reflector::InterfaceMap;

/// Run whatever the command line asked for.
///
/// `args` is the process argument list with `argv[0]` already stripped: an optional TOML config path,
/// which `NETFLECTOR_*` environment variables are merged on top of, plus `--check-config`, `--version`
/// and `--help`. Run the binary with `--help` for the full text.
///
/// # Errors
/// Returns [`Error`] if the command line is misused, if configuration loading or validation fails,
/// or if the reactor cannot be created or its event loop fails.
pub fn run(args: &[OsString]) -> Result<()> {
    match cli::parse(args)? {
        Invocation::Help => {
            print!("{}", cli::HELP);
            Ok(())
        }
        Invocation::Version => {
            println!("netflector {}", env!("CARGO_PKG_VERSION"));
            Ok(())
        }
        Invocation::CheckConfig(path) => check_config(path),
        Invocation::Run(path) => reflect(path),
    }
}

/// Load and validate the configuration, report it, and return.
///
/// Reads and validates, and does nothing else: it opens no capture and resolves no interface, so it
/// needs no privileges and runs on a machine where the configured interfaces do not exist at all. That
/// is what lets a config generated by a firewall GUI be checked on a build host. The cost is real: it
/// cannot tell you an interface is missing. The log level is left alone too, so a `log_level = "off"`
/// in the file cannot swallow the answer.
fn check_config(path: Option<&Path>) -> Result<()> {
    let toml_text = path.map(config::read_config_file).transpose()?;
    let config = Config::from_sources(toml_text.as_deref(), sys::process_env())?;
    let count = config.reflectors.len();
    println!(
        "config ok: {count} reflector{}",
        if count == 1 { "" } else { "s" }
    );
    Ok(())
}

/// Run netflector to completion.
///
/// # Errors
/// Returns [`Error`] if configuration loading or validation fails, or if the
/// reactor cannot be created or its event loop fails.
fn reflect(path: Option<&Path>) -> Result<()> {
    let toml_text = path.map(config::read_config_file).transpose()?;
    // sys::process_env, not std::env::vars: vars() segfaults in statically
    // linked FreeBSD binaries (see process_env).
    let env = sys::process_env();

    // Resolve the log level first from a minimal read of env + file, so the full parse below
    // logs at the configured verbosity (see resolve_log_level).
    logging::set_level(config::resolve_log_level(toml_text.as_deref(), &env)?);
    log::info!("netflector {} starting", env!("CARGO_PKG_VERSION"));
    if let Some(path) = path {
        log::debug!(
            "loading configuration from {} with NETFLECTOR_* overrides",
            path.display()
        );
    } else {
        log::debug!("loading configuration from NETFLECTOR_* environment only");
    }

    let config = Config::from_sources(toml_text.as_deref(), env)?;
    let count = config.reflectors.len();
    log::info!(
        "loaded {count} reflector{}",
        if count == 1 { "" } else { "s" }
    );

    // Build the data path: one capture per interface, then the reflectors that bridge them.
    let mut dispatcher = PacketDispatcher::new();
    let interfaces = open_captures(&config, &mut dispatcher)?;
    for reflector in &config.reflectors {
        crate::reflector::wol::build(reflector, &interfaces, &mut dispatcher)
            .map_err(|e| Error::reflector(reflector.name.as_str(), e))?;
        crate::reflector::mdns::build(reflector, &interfaces, &mut dispatcher)
            .map_err(|e| Error::reflector(reflector.name.as_str(), e))?;
        crate::reflector::ssdp::build(reflector, &interfaces, &mut dispatcher)
            .map_err(|e| Error::reflector(reflector.name.as_str(), e))?;
        crate::reflector::wsd::build(reflector, &interfaces, &mut dispatcher)
            .map_err(|e| Error::reflector(reflector.name.as_str(), e))?;
    }

    if let Some(interval) = config.counter_interval {
        log::info!(
            "packet counters enabled; reporting every {}s",
            interval.as_secs()
        );
        dispatcher.enable_counter_report(interval, std::time::Instant::now());
    }

    let mut reactor = Reactor::new()?;
    let watches = dispatcher.capture_watches();
    reactor.register_with_fds(Box::new(dispatcher), &watches)?;
    if let Some(interval) = config.debug_memory_interval {
        log::info!(
            "memory diagnostics enabled; reporting every {}s",
            interval.as_secs()
        );
        memory_report::log_report(); // a baseline before the loop starts
    }
    // Always registered: reports periodically only when an interval is configured, but dumps on a
    // SIGUSR1 control event regardless. Memory stats are always cheaply available.
    reactor.register(Box::new(memory_report::MemoryReporter::new(
        config.debug_memory_interval,
        std::time::Instant::now(),
    )));
    log::info!("running; press Ctrl-C or send SIGTERM to stop");
    reactor.run()?;
    if config.debug_memory_interval.is_some() {
        memory_report::log_report(); // a final report at shutdown
    }
    log::info!("stopped");
    Ok(())
}

/// Open one capture per distinct interface: the `source ∪ target` of every reflector, in
/// first-seen order. Records each in an [`InterfaceMap`] for the per-protocol builders.
/// Fail-closed: a capture that can't open (missing `CAP_NET_RAW`, an absent interface) aborts
/// startup, since a daemon that looks healthy but reflects nothing is worse.
fn open_captures(config: &Config, dispatcher: &mut PacketDispatcher) -> Result<InterfaceMap> {
    let mut interfaces = InterfaceMap::default();
    for reflector in &config.reflectors {
        for name in [reflector.source_if.as_str(), reflector.target_if.as_str()] {
            if interfaces.key_for(name).is_some() {
                continue;
            }
            let capture = Capture::open(name).map_err(|e| Error::capture(name, e))?;
            let key = dispatcher
                .add_capture(capture)
                .map_err(|e| Error::capture(name, e))?;
            interfaces.insert(name.to_owned(), key);
        }
    }
    Ok(interfaces)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_config_accepts_a_valid_file_and_rejects_a_bad_one() {
        // The whole point of --check-config is that it runs where the interfaces do not exist, so
        // this must pass on any host, unprivileged, with no vtnet0 anywhere in sight.
        let good = "[reflectors.tv]\nsource_if = \"vtnet0\"\ntarget_if = \"vtnet1\"\nmdns = true\n";
        let config = Config::from_sources(Some(good), Vec::new()).unwrap();
        assert_eq!(config.reflectors.len(), 1);

        // An entry that enables no protocol reflects nothing; that is a config error, not a daemon
        // that quietly does nothing.
        let bad = "[reflectors.tv]\nsource_if = \"vtnet0\"\ntarget_if = \"vtnet1\"\n";
        assert!(Config::from_sources(Some(bad), Vec::new()).is_err());
    }
}
